### PR TITLE
Add typechat to example package deps

### LINKED ISSUE #81: all samples package.json do not have typechat as a dependency
Not sure if this is intentional or not but the `package.json` in each of the samples is missing the dependency for typechat. 

i.e. [https://github.com/microsoft/TypeChat/blob/main/examples/calendar/package.json](https://github.com/microsoft/TypeChat/blob/main/examples/calendar/package.json)

### PR DESCRIPTION
**Pull request by jakebailey**
This is an alternative to #89, and also fixes #81.

This worked for me but not for @DanielRosenwasser; I did see a bunch of time spent idealTree-ing but that happens when you change the tree, it seems.

There are other reasons to take #89 instead, mainly, perf.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
It works, but my issue was that if you run with a specific `install-strategy` in an `.npmrc`, that doesn't seem to do anything different than usual. It appears that everything gets hoisted.

**Comment by jakebailey** [comment]
The layouts you get between this PR and the pnpm one are the same; you get hoisted to the top no matter what, so I'm not sure what you're observing that's different/bad exactly.

**Comment by DanielRosenwasser** [comment]
My assumption was that pnpm creates a specific `node_modules` directory per package which ends up being "stricter". The two main things which that helps with is:

1. pnpm will not directly expose a package that an example relies on (like `dotenv`) to `typechat` itself
1. examples that don't explicitly depend on `typechat` will not be able to access it

**Comment by jakebailey** [comment]
It may or may not do either because you're using the monorepo root as an actual package with dependencies. It's impossible for an example to _not_ see `axios`, for example; it's there in the parent directory, and you can't fix that without using the more typical layout which moves everything into `packages/*` or something.

But, it is at least _more unlikely_ that you'll accidentally use a package that hasn't been declared thanks to pnpm not linking anything but declared ones.

In this repo's case, I believe you will get an error if typechat is not listed even though it's a parent because pnpm doesn't (yet) automatically create self-links like npm/yarn do.

**Pull request merged**
